mqtt:
  broker: "pccmslab1"
  port: 1883
MARTA:
  mqtt_topic: "/MARTA/#"
Coldroom:
  mqtt_topic: "/coldroom/#"
  co2_sensor_topic: "/ble/CO2-1"
ThermalCamera:
  mqtt_topic: "/thermalcamera/#"
  stitch_camera: "camera0"
